import source from "./music-source.json";

export type MusicEntry = {
  key: string;
  artist: string;
  title: string;
  kind: "album" | "single";
  itunesId: number;
  /** Committed pixelated cover, generated by scripts/pixelart/gen-albums.mjs */
  art: string;
};

export const MUSIC: MusicEntry[] = source.map((e) => ({
  ...e,
  kind: e.kind as MusicEntry["kind"],
  art: `/3am/albums/${e.key}.png`,
}));
